name: 'Run xcodebuild test'
description: 'Action runs the test for the scheme specified'

inputs:
  scheme:
    required: true
    type: string
  destination:
    required: false
    type: string
    default: 'platform=iOS Simulator,name=iPhone 13,OS=latest'

runs:
  using: "composite"
  steps:
    - name: Test ${{ inputs.scheme }}
      run: |
        xcodebuild test -scheme ${{ inputs.scheme }} -sdk iphonesimulator -destination '${{ inputs.destination }}' | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]}        
      shell: bash 
